package com.example.logifitappp.enums

enum class NotificationSpecTypeEnum {
    AMAZON,
    ANTOX,
    BBM,
    BUSINESS_CALENDAR,
    COL_REMINDER,
    CONVERSATIONS,
    DELTACHAT,
    DISCORD,
    ELEMENT,
    ELEMENTX,
    FACEBOOK,
    FACEBOOK_MESSENGER,
    GENERIC_ALARM_CLOCK,
    GENERIC_CALENDAR,
    GENERIC_EMAIL,
    GENERIC_NAVIGATION,
    GENERIC_PHONE,
    GENERIC_SMS,
    GMAIL,
    GOOGLE_HANGOUTS,
    GOOGLE_INBOX,
    GOOGLE_MAPS,
    GOOGLE_MESSENGER,
    GOOGLE_PHOTOS,
    HIPCHAT,
    INSTAGRAM,
    KAKAO_TALK,
    KIK,
    KONTALK,
    LIGHTHOUSE,
    LINE,
    LINKEDIN,
    MAILBOX,
    MOLLY,
    OUTLOOK,
    RIOT,
    SIGNAL,
    SKYPE,
    SLACK,
    SNAPCHAT,
    TELEGRAM,
    THREEMA,
    TRANSIT,
    TWITTER,
    UNKNOWN,
    VIBER,
    WECHAT,
    WHATSAPP,
    WIRE,
    YAHOO_MAIL;

    fun getGenericType() = when (this) {
        GENERIC_EMAIL, GENERIC_NAVIGATION, GENERIC_SMS, GENERIC_PHONE, GENERIC_CALENDAR, GENERIC_ALARM_CLOCK -> name.lowercase()
        FACEBOOK, TWITTER, SNAPCHAT, INSTAGRAM, LINKEDIN -> "generic_social"

        CONVERSATIONS, FACEBOOK_MESSENGER, RIOT, SIGNAL, WIRE, TELEGRAM, THREEMA, KONTALK,
        ANTOX, WHATSAPP, GOOGLE_MESSENGER, GOOGLE_HANGOUTS, HIPCHAT, SKYPE, WECHAT, KIK, KAKAO_TALK,
        SLACK, LINE, VIBER, DISCORD, DELTACHAT, ELEMENT, ELEMENTX, MOLLY -> "generic_chat"

        GMAIL, GOOGLE_INBOX, MAILBOX, OUTLOOK, YAHOO_MAIL -> "generic_email"
        COL_REMINDER, UNKNOWN -> "generic"
        else -> "generic"
    }
}