package com.example.logifitappp.core

import com.example.logifitappp.enums.NotificationSpecTypeEnum

class AppNotificationMap: HashMap<String, NotificationSpecTypeEnum>() {
    init {
        put("com.fsck.k9", NotificationSpecTypeEnum.GENERIC_EMAIL)
        put("com.fsck.k9.material", NotificationSpecTypeEnum.GENERIC_EMAIL)
        put("com.imaeses.squeaky", NotificationSpecTypeEnum.GENERIC_EMAIL)
        put("com.android.email", NotificationSpecTypeEnum.GENERIC_EMAIL)
        put("ch.protonmail.android", NotificationSpecTypeEnum.GENERIC_EMAIL)
        put("security.pEp", NotificationSpecTypeEnum.GENERIC_EMAIL)
        put("eu.faircode.email", NotificationSpecTypeEnum.GENERIC_EMAIL)
        put("com.moez.QKSMS", NotificationSpecTypeEnum.GENERIC_SMS)
        put("com.android.mms", NotificationSpecTypeEnum.GENERIC_SMS)
        put("com.android.messaging", NotificationSpecTypeEnum.GENERIC_SMS)
        put("com.sonyericsson.conversations", NotificationSpecTypeEnum.GENERIC_SMS)
        put("org.smssecure.smssecure", NotificationSpecTypeEnum.GENERIC_SMS)
        put("com.android.calendar", NotificationSpecTypeEnum.GENERIC_CALENDAR)
        put("mikado.bizcalpro", NotificationSpecTypeEnum.BUSINESS_CALENDAR)
        put("com.google.android.gm", NotificationSpecTypeEnum.GMAIL)
        put("com.google.android.apps.inbox", NotificationSpecTypeEnum.GOOGLE_INBOX)
        put("com.google.android.calendar", NotificationSpecTypeEnum.GENERIC_CALENDAR)
        put("com.google.android.apps.messaging", NotificationSpecTypeEnum.GOOGLE_MESSENGER)
        put("com.google.android.talk", NotificationSpecTypeEnum.GOOGLE_HANGOUTS)
        put("com.google.android.apps.maps", NotificationSpecTypeEnum.GOOGLE_MAPS)
        put("com.google.android.apps.photos", NotificationSpecTypeEnum.GOOGLE_PHOTOS)
        put("com.google.android.apps.googlevoice", NotificationSpecTypeEnum.GENERIC_SMS)
        put("eu.siacs.conversations", NotificationSpecTypeEnum.CONVERSATIONS)
        put("de.pixart.messenger", NotificationSpecTypeEnum.CONVERSATIONS)
        put("im.vector.alpha", NotificationSpecTypeEnum.RIOT)
        put("im.vector.app", NotificationSpecTypeEnum.ELEMENT)
        put("io.element.android.x", NotificationSpecTypeEnum.ELEMENTX)
        put("org.thoughtcrime.securesms", NotificationSpecTypeEnum.SIGNAL)
        put("im.molly.app", NotificationSpecTypeEnum.MOLLY)
        put("im.molly.app.unifiedpush", NotificationSpecTypeEnum.MOLLY)
        put("com.wire", NotificationSpecTypeEnum.WIRE)
        put("org.telegram.messenger", NotificationSpecTypeEnum.TELEGRAM)
        put("org.telegram.messenger.beta", NotificationSpecTypeEnum.TELEGRAM)
        put("org.telegram.messenger.web", NotificationSpecTypeEnum.TELEGRAM)
        put("org.telegram.plus", NotificationSpecTypeEnum.TELEGRAM)
        put("org.thunderdog.challegram", NotificationSpecTypeEnum.TELEGRAM)
        put("nekox.messenger", NotificationSpecTypeEnum.TELEGRAM)
        put("ch.threema.app", NotificationSpecTypeEnum.THREEMA)
        put("org.kontalk", NotificationSpecTypeEnum.KONTALK)
        put("chat.tox.antox", NotificationSpecTypeEnum.ANTOX)
        put("org.mariotaku.twidere", NotificationSpecTypeEnum.TWITTER)
        put("com.twitter.android", NotificationSpecTypeEnum.TWITTER)
        put("org.andstatus.app", NotificationSpecTypeEnum.TWITTER)
        put("org.mustard.android", NotificationSpecTypeEnum.TWITTER)
        put("me.zeeroooo.materialfb", NotificationSpecTypeEnum.FACEBOOK)
        put("it.rignanese.leo.slimfacebook", NotificationSpecTypeEnum.FACEBOOK)
        put("me.jakelane.wrapperforfacebook", NotificationSpecTypeEnum.FACEBOOK)
        put("com.facebook.katana", NotificationSpecTypeEnum.FACEBOOK)
        put("org.indywidualni.fblite", NotificationSpecTypeEnum.FACEBOOK)
        put("com.facebook.orca", NotificationSpecTypeEnum.FACEBOOK_MESSENGER)
        put("com.facebook.mlite", NotificationSpecTypeEnum.FACEBOOK_MESSENGER)
        put("com.whatsapp", NotificationSpecTypeEnum.WHATSAPP)
        put("com.hipchat", NotificationSpecTypeEnum.HIPCHAT)
        put("com.skype.raider", NotificationSpecTypeEnum.SKYPE)
        put("com.microsoft.office.lync15", NotificationSpecTypeEnum.SKYPE)
        put("com.mailboxapp", NotificationSpecTypeEnum.MAILBOX)
        put("com.snapchat.android", NotificationSpecTypeEnum.SNAPCHAT)
        put("com.tencent.mm", NotificationSpecTypeEnum.WECHAT)
        put("com.viber.voip", NotificationSpecTypeEnum.VIBER)
        put("com.instagram.android", NotificationSpecTypeEnum.INSTAGRAM)
        put("kik.android", NotificationSpecTypeEnum.KIK)
        put("jp.naver.line.android", NotificationSpecTypeEnum.LINE)
        put("com.bbm", NotificationSpecTypeEnum.BBM)
        put("com.microsoft.office.outlook", NotificationSpecTypeEnum.OUTLOOK)
        put("com.appgenix.bizcal", NotificationSpecTypeEnum.BUSINESS_CALENDAR)
        put("com.yahoo.mobile.client.android.mail", NotificationSpecTypeEnum.YAHOO_MAIL)
        put("com.kakao.talk", NotificationSpecTypeEnum.KAKAO_TALK)
        put("com.amazon.mshop.android.shopping", NotificationSpecTypeEnum.AMAZON)
        put("com.linkedin.android", NotificationSpecTypeEnum.LINKEDIN)
        put("com.slack", NotificationSpecTypeEnum.SLACK)
        put("com.thetransitapp.droid", NotificationSpecTypeEnum.TRANSIT)
        put("ws.xsoh.etar", NotificationSpecTypeEnum.GENERIC_CALENDAR)
        put("com.discord", NotificationSpecTypeEnum.DISCORD)
        put("com.colapps.reminder", NotificationSpecTypeEnum.COL_REMINDER)
        put("com.b44t.messenger", NotificationSpecTypeEnum.DELTACHAT)
        put("org.kde.itinerary", NotificationSpecTypeEnum.TRANSIT)
        put("org.kde.ktrip", NotificationSpecTypeEnum.TRANSIT)
    }

    companion object {
        private var instance: AppNotificationMap? = null

        fun getInstance(): AppNotificationMap {
            if (instance == null) instance = AppNotificationMap()

            return instance!!
        }
    }
}